<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
// echo get_class($block);
?>
<?php
$_product = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');

$enable_ajax = $this->helper('Rahul\Wishlist\Helper\Data')->isEnable();
?>

<div class="product-addto-links" data-role="add-to-links">
    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
        <a href="#"
            class="action towishlist"
            data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
            data-action="add-to-wishlist"><span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span></a>
    <?php endif; ?>
    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
        data-role="add-to-links"
        class="action tocompare"><span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span></a>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
        }
    }
</script>

<?php if($enable_ajax)  : ?>
<script type="text/javascript">
    require([
        "jquery"
        ], function($){
            $(document).ready(function(){
                $('.towishlist').click(function(event){
                    event.preventDefault();
                    event.stopPropagation();
                    var data = $(this).attr('data-post');
                    var obj = jQuery.parseJSON(data);
                    // console.log(obj);
                    // console.log(obj.action);

                    $.ajax({
                    url : obj.action,
                    data : {'product':obj.data},
                    type : "post",
                    dataType : 'json',
                    showLoader:true,
                    success : function(data)
                    {
                        console.log(data);
                       if(data.status == 'not_logged_in'){
                         window.location.href = "<?php echo $block->getLoginUrl(); ?>";
                       }
                    }
                });
                });
            });
        });
</script>
<?php endif ; ?>
